name: Teste de infra pré-produção

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Teste de infra em PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Construir pacote Lambda
        run: |
          sh scripts/build_lambda_package.sh

      - name: Aplicar IaC
        run: |
          cd infrastructure
          terraform init
          terraform validate
          terraform plan
